baseurl = "https://emre-dundar.com/"
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
paginate = 5
preserveTaxonomyNames = true
publishDir = "/home/kureta/srv/emre-dundar.com"
theme = "nederburg"
title = "Emre Dundar"
[[menu.main]]
name = "Contact"
url = "contact/"
weight = 3
[[menu.main]]
name = "About"
url = "about/"
weight = 2
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[params]
author = "Emre Dundar"
bio = ["Emre Dundar is an accomplished composer from Istanbul. He focuses on musical representations of various aspects of spoken languages."]
copyright = ["&copy; 2019 Emre Dundar"]
description = "Personal and professional website of composer Emre Dundar"
email = "emre@emre-dundar.com"
slogan = "De Vulgari Eloquentia "
[params.social]
email = "emre@emre-dundar.com"
facebook = "full Social profile url in facebook"
github = "full profile url in github"
googleplus = "full profile url in googleplus"
instagram = "full profile url in instagram"
linkedin = "full profile url in linkedin"
pinterest = "full profile url in pinterest"
rss = true
stackoverflow = "full profile url in stackoverflow"
twitter = "full profile url in twitter"
[params.writers."Emre Dundar"]
bio = ["Emre Dundar is an accomplished composer from Istanbul. He focuses on musical representations of various aspects of spoken languages."]
email = "emre@emre-dundar.com"
facebook = "full Göran profile url in facebook"
github = "full profile url in github"
googleplus = "full profile url in googleplus"
instagram = "full profile url in instagram"
linkedin = "full profile url in linkedin"
pinterest = "full profile url in pinterest"
stackoverflow = "full profile url in stackoverflow"
twitter = "full profile url in twitter"
