baseurl = "http://emre-dundar.com/"
publishDir = "/home/kureta/srv/emre-dundar.com"
title = "Emre Dundar"
theme = "nederburg"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination

[params]
  slogan = "De Vulgari Eloquentia "
  description = "Personal and professional website of composer Emre Dundar" # meta description
  # You need to set author to have an author bio. If you have a writer in the markdown file it will override this.
  author = "Emre Dundar"
  # authorLink = "https://appernetic.io/"
  bio = [
    "Emre Dundar is an accomplished composer from Istanbul. He focuses on musical representations of various aspects of spoken languages."
  ]
  copyright = [
    "&copy; 2019 Emre Dundar"
  ]


  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below (it is also used in Gravatar for the bio).
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "emre@emre-dundar.com"

  # Nav links in the side bar
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "About"
  url = "about/"
  weight = 2

  [[menu.main]]
  name = "Contact"
  url = "contact/"
  weight = 3

# this will also be in author bio if there is no writer.
  [params.social]
  facebook      = "full Social profile url in facebook"
  googleplus    = "full profile url in googleplus"
  email         = "emre@emre-dundar.com"
  twitter       = "full profile url in twitter"
  linkedin      = "full profile url in linkedin"
  stackoverflow = "full profile url in stackoverflow"
  instagram     = "full profile url in instagram"
  github        = "full profile url in github"
  pinterest     = "full profile url in pinterest"
  rss           = true

